from pathlib import Path
from typing import Dict, List, Tuple
import re


class Scanner:
    """Lightweight repository scanner that collects file counts, LOC, and suspicious patterns."""

    SUSPICIOUS_PATTERNS = [
        r"\beval\(",
        r"\bexec\(",
        r"password",
        r"secret",
        r"aws_access_key",
        r"aws_secret",
        r"TODO",
        r"FIXME",
    ]

    # directories to ignore as boilerplate/vendor/generated
    BOILERPLATE_DIRS = {
        "node_modules",
        "__pycache__",
        ".venv",
        "venv",
        "dist",
        "build",
        "platform/generated",
        "platform/frontend/node_modules",
    }

    # file content patterns that indicate generated or boilerplate files
    BOILERPLATE_CONTENT_PATTERNS = [
        r"DO NOT EDIT",
        r"@generated",
        r"generated by",
        r"this file is generated",
    ]

    # small heuristics to detect language from content when extension is missing or ambiguous
    @staticmethod
    def detect_language_from_content(text: str, ext: str) -> str:
        if ext == ".py" or text.lstrip().startswith("#!") and "python" in text[:200].lower():
            return "python"
        low = text.lower()
        if "<?php" in low:
            return "php"
        if "import " in low and "def " in low and (ext == ".py" or ext == ""):
            return "python"
        if "function " in low or "const " in low or "require(" in low or "module.exports" in low:
            return "javascript"
        if "#include" in low or "int main(" in low:
            return "c/c++"
        if "package " in low and "func " in low:
            return "go"
        return ""

    def __init__(self, root: Path):
        self.root = Path(root)

    def scan(self) -> Dict:
        files_by_ext = {}
        loc_by_ext = {}
        files_by_lang: Dict[str, int] = {}
        loc_by_lang: Dict[str, int] = {}
        findings: List[Tuple[str, int, str]] = []
        boilerplate_files: List[str] = []

        for path in self.root.rglob("*"):
            if path.is_file():
                try:
                    # skip common vendor/generated directories
                    parts = set(p.name for p in path.parents)
                    if parts & self.BOILERPLATE_DIRS:
                        boilerplate_files.append(str(path.relative_to(self.root)))
                        continue

                    ext = path.suffix.lower() or ""

                    # attempt to read text files for LOC and patterns
                    text = path.read_text(encoding="utf-8", errors="ignore")

                    # detect boilerplate by content
                    for pat in self.BOILERPLATE_CONTENT_PATTERNS:
                        if re.search(pat, text, re.IGNORECASE):
                            boilerplate_files.append(str(path.relative_to(self.root)))
                            raise StopIteration

                    lines = text.splitlines()
                    files_by_ext[ext] = files_by_ext.get(ext, 0) + 1
                    loc_by_ext[ext] = loc_by_ext.get(ext, 0) + len(lines)

                    # language detection fallback
                    content_lang = self.detect_language_from_content(text, ext)
                    lang_key = content_lang or ext.lstrip(".") or "other"
                    files_by_lang[lang_key] = files_by_lang.get(lang_key, 0) + 1
                    loc_by_lang[lang_key] = loc_by_lang.get(lang_key, 0) + len(lines)

                    # scan for suspicious patterns
                    for i, line in enumerate(lines, start=1):
                        for pat in self.SUSPICIOUS_PATTERNS:
                            if re.search(pat, line, re.IGNORECASE):
                                findings.append((str(path.relative_to(self.root)), i, line.strip()))
                                break

                except StopIteration:
                    # intentionally skipped as boilerplate
                    continue
                except Exception:
                    # binary or unreadable file: count it but skip content
                    ext = path.suffix.lower() or "noext"
                    files_by_ext[ext] = files_by_ext.get(ext, 0) + 0

        return {
            "files_by_ext": files_by_ext,
            "loc_by_ext": loc_by_ext,
            "files_by_lang": files_by_lang,
            "loc_by_lang": loc_by_lang,
            "findings": findings,
            "boilerplate_files": boilerplate_files,
        }
