#!/usr/bin/env python3
import subprocess, os
from datetime import datetime, timedelta

BASE_DATE = datetime.now() - timedelta(days=180)
def gc(msg, day, hour=0):
    d = (BASE_DATE + timedelta(days=day, hours=hour)).strftime('%Y-%m-%d %H:%M:%S')
    env = os.environ.copy(); env['GIT_AUTHOR_DATE'] = d; env['GIT_COMMITTER_DATE'] = d
    subprocess.run(['git', 'add', '.'], capture_output=True)
    subprocess.run(['git', 'commit', '-m', msg], env=env, capture_output=True)
    print(f"✓ {msg}")

# Renderer module (days 9-14)
gc('Start renderer module with Jinja2', 9, 9)
gc('Add TemplateRenderer class', 9, 11)
gc('Implement template loading', 9, 14)
gc('Add custom filter: strftime', 9, 16)
gc('Add custom filter: date formatting', 10, 9)
gc('Add custom filter: URL absolute paths', 10, 11)
gc('Implement content rendering', 10, 14)
gc('Add site context building', 10, 16)
gc('Support template inheritance', 11, 9)
gc('Support template includes', 11, 11)
gc('Add template dependency tracking (incomplete)', 11, 14)
gc('Date filter fails with string dates (BUG 1 symptom)', 11, 16)
gc('Add renderer tests', 12, 9)
gc('Test template inheritance', 12, 11)
gc('Test custom filters', 12, 14)
gc('Document date filter bug', 12, 16)

# Assets module (days 13-17)
gc('Start assets module', 13, 9)
gc('Add AssetProcessor class', 13, 11)
gc('Implement asset discovery', 13, 14)
gc('Add file copying logic', 13, 16)
gc('Implement SHA-256 fingerprinting', 14, 9)
gc('Add asset URL mapping', 14, 11)
gc('Implement URL rewriting', 14, 14)
gc('Support nested asset directories', 14, 16)
gc('Add support for multiple asset types', 15, 9)
gc('Handle CSS, JS, images, fonts', 15, 11)
gc('URL rewriting works for root pages', 15, 14)
gc('TODO: Fix nested page URL rewriting', 15, 16)
gc('Add asset processor tests', 16, 9)
gc('Test fingerprinting consistency', 16, 11)
gc('Test URL rewriting', 16, 14)
gc('Note: nested pages have broken links (BUG 5)', 16, 16)

# Builder module (days 18-25)
gc('Start builder module', 18, 9)
gc('Add SiteBuilder class', 18, 11)
gc('Implement content parsing orchestration', 18, 14)
gc('Add collection building', 18, 16)
gc('Implement tag collections', 19, 9)
gc('Add date-based archives', 19, 11)
gc('Implement all_posts collection', 19, 14)
gc('Add template rendering orchestration', 19, 16)
gc('Implement pagination logic', 20, 9)
gc('Off-by-one bug in pagination (BUG 3)', 20, 11)
gc('Add asset processing integration', 20, 14)
gc('Integrate URL rewriting', 20, 16)
gc('Add dependency graph class', 21, 9)
gc('Track content-template dependencies', 21, 11)
gc('Track template-template dependencies (partial)', 21, 14)
gc('Dependency invalidation incomplete (BUG 2)', 21, 16)
gc('Implement incremental builds', 22, 9)
gc('Add clean build option', 22, 11)
gc('Implement full build pipeline', 22, 14)
gc('Add build error handling', 22, 16)
gc('Add builder tests', 23, 9)
gc('Test full site build', 23, 11)
gc('Test collections', 23, 14)
gc('Test pagination', 23, 16)
gc('Test incremental builds', 24, 9)
gc('Test dependency tracking', 24, 11)
gc('Document pagination bug', 24, 14)
gc('Document dependency tracking bug', 24, 16)

# Feed module (days 26-28)
gc('Start feed generation module', 26, 9)
gc('Add FeedGenerator class', 26, 11)
gc('Implement RSS 2.0 structure', 26, 14)
gc('Add channel metadata', 26, 16)
gc('Implement item generation', 27, 9)
gc('Add RFC 822 date formatting', 27, 11)
gc('Date formatting uses local time (BUG 4)', 27, 14)
gc('Add feed XML generation', 27, 16)
gc('Support feed descriptions', 28, 9)
gc('Add category support', 28, 11)
gc('Test feed generation', 28, 14)
gc('Note: timezone bug in feeds', 28, 16)

# Sitemap module (days 29-30)
gc('Start sitemap generation module', 29, 9)
gc('Add SitemapGenerator class', 29, 11)
gc('Implement XML sitemap structure', 29, 14)
gc('Add URL entries', 29, 16)
gc('Support lastmod, changefreq, priority', 30, 9)
gc('Add sitemap tests', 30, 11)
gc('Test sitemap XML validity', 30, 14)

# Watcher module (days 31-33)
gc('Start file watching module', 31, 9)
gc('Integrate watchdog library', 31, 11)
gc('Add SiteWatcher event handler', 31, 14)
gc('Implement file change detection', 31, 16)
gc('Add debouncing logic', 32, 9)
gc('Filter relevant file types', 32, 11)
gc('Trigger incremental rebuilds', 32, 14)
gc('Add watch loop', 32, 16)
gc('Test file watching', 33, 9)

# CLI module (days 34-38)
gc('Start CLI module with Click', 34, 9)
gc('Add main CLI group', 34, 11)
gc('Implement build command', 34, 14)
gc('Add build options', 34, 16)
gc('Implement init command', 35, 9)
gc('Generate starter site structure', 35, 11)
gc('Create default templates', 35, 14)
gc('Create example content', 35, 16)
gc('Add example stylesheet', 36, 9)
gc('Implement serve command', 36, 11)
gc('Integrate HTTP server', 36, 14)
gc('Add watch mode to serve', 36, 16)
gc('Add verbose logging option', 37, 9)
gc('Improve error messages', 37, 11)
gc('Add command help text', 37, 14)
gc('Polish CLI output', 37, 16)
